---
- hosts: targetservers
  tasks:

    - name: install epel release repo
      yum: name=epel-release state=installed

    - name: remove anacron
      yum: name=cronie-anacron state=removed
   
    - name: remove network-manager
      yum: name=network-manager state=removed

    - name: Restart network service
      service: name=network

    - name: install noanacron 
      yum: name=cronie-noanacron state=installed

    - name: update the system
      yum: name='*' state=installed

    - name: install utils (net-tools, bind-utils, nano, unzip, rar, unrar, mtr)
      yum: name={{ item }} state=installed
      with_items: 
        - net-tools
        - bind-utils
        - nano 
        - unzip 
        - mtr
        - nc
        - wget
            
    - name: install tools fo troubleshooting
      yum: name={{ item }} state=installed
      with_items:
        - strace
        - psmisc
        - lsof
        - atop
        - htop

    - name: install tools for kernel installs
      yum: name={{ item }} state=installed
      with_items:
        - gcc
        - perl
        - bc
        - ncurses-devel

 
    - name: some sysctl changes
      sysctl: name="{{ item.name }}" value="{{ item.value }}" sysctl_set=yes state=present
      with_items:
        - { name: 'net.core.somaxconn', value: 1024 }   
        - { name: 'net.core.rmem_max', value: 8388608 }
        - { name: 'net.core.wmem_max', value: 8388608 }
        - { name: 'net.core.rmem_default', value: 65536 }
        - { name: 'net.core.wmem_default', value: 65536 }
        - { name: 'net.ipv4.conf.all.accept_redirects', value: 0 }
        - { name: 'net.ipv4.conf.all.secure_redirects', value: 0 }
        - { name: 'net.ipv4.tcp_max_orphans', value: 65536 }
        - { name: 'net.ipv4.tcp_fin_timeout', value: 10 }
        - { name: 'net.ipv4.tcp_keepalive_time', value: 1800 }
        - { name: 'net.ipv4.tcp_keepalive_intvl', value: 15 }
        - { name: 'net.ipv4.tcp_keepalive_probes', value: 5 }
        - { name: 'net.ipv4.tcp_syncookies', value: 0 }
        - { name: 'net.ipv4.conf.all.rp_filter', value: 1 }
        - { name: 'net.ipv4.conf.lo.rp_filter', value: 1 }
        - { name: 'net.ipv4.conf.eth0.rp_filter', value: 1 }
        - { name: 'net.ipv4.conf.default.rp_filter', value: 1 }
        - { name: 'net.ipv4.tcp_rmem', value: 4096 87380 16777216 }
        - { name: 'net.ipv4.tcp_wmem', value: 4096 65536 16777216 }
        - { name: 'net.ipv4.tcp_mem', value: 16777216 16777216 16777216 }
        - { name: 'vm.swappiness', value: 1 }
