# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "router-net"},
                ]
  },
  
 :inetRouter2 => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "router-net"},
                ]
  },
 

  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   
                ]
  },
  
    :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   
                ]
  },
  
      :ansibleServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.3', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dir-net"},
                   
                ]
  },

}
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
			sudo iptables -t nat -A POSTROUTING -s 192.168.255.0/26 -j MASQUERADE
			ip route add 192.168.0.0/28 via 192.168.255.2
			sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			service sshd restart
            SHELL

        when "inetRouter2"
		box.vm.network "forwarded_port", guest: 8080, host: 8080
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
			ip route add 192.168.0.0/28 via 192.168.255.2
			sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			service sshd restart
            SHELL

        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            service network restart
			sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			service sshd restart
			sysctl net.ipv4.conf.all.forwarding=1
			
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			service sshd restart
            systemctl restart network
            SHELL
        when "ansibleServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
			sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
			service sshd restart
            systemctl restart network
			yum -y install ansible
			cd /vagrant
			cp hosts nginx_publishing /home/vagrant/
            SHELL
		
        end

      end

  end
  
  
end

